version: '{build}'

environment:
  install_dir: C:\Projects\install\windows-env

platform:
  - i386
  - x86_64

matrix:
  fast_finish: true

before_build:
  - choco.exe install haskell-stack

build_script:
  - >-
    stack.exe
    build
    --install-ghc
    --copy-bins
    --local-bin-path "%install_dir%"
    --arch "%PLATFORM%"

after_build:
  - 7z.exe a "%APPVEYOR_PROJECT_NAME%-%PLATFORM%.zip" "%install_dir%"
  - appveyor.exe PushArtifact "%APPVEYOR_PROJECT_NAME%-%PLATFORM%.zip"
