resolver: lts-7.11
packages:
- .
- location: https://github.com/haskell/win32/archive/bf54fa7134eb9b1366f827426f050d833b2cda54.zip
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
allow-newer: true
system-ghc: false
# require-stack-version: -any # Default
# require-stack-version: ">=1.1"
# arch: i386
# arch: x86_64
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
# compiler-check: newer-minor
